[package]
name = "chain-signatures"
version = "0.1.0"
edition = "2021"

[dependencies]
# Chain signatures library doesn't need near-sdk since it's not a contract
serde = { workspace = true }
serde_json = { workspace = true }

[lib]
crate-type = ["rlib"]