[package]
name = "chain-signatures"
version = "0.1.0"
edition = "2021"

[dependencies]
near-sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lib]
crate-type = ["rlib"]